# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r XieXianbin/pac4j-plus --add env.global
#

language: java
sudo: required
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.gradle/caches'
git:
  depth: 3
env:
  global:
  - secure: "cDN6+bwe7NVMjvevGMwk9tdglhGf66yi3nvbnfSgio207FuNG4duF/RNOUOMsuWX1Sc79ZMDuOttZ5AvL3ZHKPtmzTBMvCdDkf1FwFmzU6N+x84rT4zyos+gZLgHbV0M0M28y8aJIJq2kcwiqVwuMBay5tjrpJ8IMPoY6eDl4uE="
before_script:
 - export JAVA_OPTS="-Xmx2048m"
before_install:
- git gc --aggressive --prune=now
- ls ./etc
- sudo unzip -j -o ./etc/jce8.zip *.jar -d `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo ls `jdk_switcher home oraclejdk8`/jre/lib/security
- sudo cp ./etc/java.security `jdk_switcher home oraclejdk8`/jre/lib/security
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
- chmod -R 777 ./gradlew
install:
- ./gradlew clean bootRepackage install --parallel -x test --stacktrace
script:
- travis_wait sudo ./gradlew checkstyleTest test --stacktrace --parallel
after_success:
- chmod -R 777 ./travis/push-javadoc-to-gh-pages.sh
- ./travis/push-javadoc-to-gh-pages.sh
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
